server_name: body

port: 4222
http: 8222

jetstream {
  enabled: true
  store_dir: /data/nats
}

write_deadline: 5s
ping_interval: 20s
ping_max: 3
max_payload: 64MB

leafnodes {
  port: 7422
}

websocket {
  port: 9222
  same_origin: false
  compression: true

  tls {
    cert_file: "/etc/cert/cert.pem"
    key_file: "/etc/cert/key.pem"
  }
}

accounts {
  SYS {
    users = [
      { user: "rabbit", password: "rabbit" }
    ]
  }
}

system_account: SYS