server_name: brain

port: 4222
http: 8222

write_deadline: 5s
ping_interval: 20s
ping_max: 3
max_payload: 64MB

leafnodes {
  reconnect: 1
  remotes = [
    { url: "nats-leaf://10.77.0.1:7422" }
  ]
}
