x-logging: &logging
  driver: json-file
  options:
    max-size: 20m
    max-file: '3'

services:
  nats:
    logging: *logging
    image: nats:latest
    container_name: nats
    command: -c /etc/nats/nats-server.conf
    volumes:
      - ./nats/nats-server.conf:/etc/nats/nats-server.conf:ro
      - ./nats/data:/data/nats
      - ../cert:/etc/cert:ro
    restart: unless-stopped
    ports:
      - '4222:4222'
      - '9222:9222'
      - '8222:8222'
    healthcheck:
      test: ['CMD', 'nats', 'server', 'ping', '--server=nats://localhost:4222']
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  nats-init:
    logging: *logging
    image: bitnami/natscli
    depends_on:
      - nats
    volumes:
      - ./nats/init.sh:/init.sh
    entrypoint: ['/bin/bash', '/init.sh']
    restart: 'no'

  rabbit-zed:
    logging: *logging
    build:
      context: ./rabbit
      dockerfile: ./docker/Dockerfile.zed
    container_name: rabbit-zed
    stop_grace_period: 30s
    privileged: true
    working_dir: /rabbit
    runtime: nvidia
    volumes:
      - ./rabbit:/rabbit
      - /dev:/dev
      - /tmp/argus_socket:/tmp/argus_socket
      - ../../zed/settings:/usr/local/zed/settings
      - ../../zed/resources:/usr/local/zed/resources
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    restart: unless-stopped
    command: uv run src/node/zed.py
    depends_on:
      - nats-init

  rabbit-roboclaw:
    logging: *logging
    build:
      context: ./rabbit
      dockerfile: ./docker/Dockerfile.zed
    container_name: rabbit-roboclaw
    privileged: true
    working_dir: /rabbit
    volumes:
      - ./rabbit:/rabbit
      - /dev:/dev
    restart: unless-stopped
    command: uv run src/node/roboclaw.py

  rabbit-steering:
    logging: *logging
    build:
      context: ./rabbit
      dockerfile: ./docker/Dockerfile.zed
    container_name: rabbit-steering
    privileged: true
    working_dir: /rabbit
    volumes:
      - ./rabbit:/rabbit
    restart: unless-stopped
    command: uv run src/node/steering.py

  rabbit-nav:
    logging: *logging
    build:
      context: ./rabbit
      dockerfile: ./docker/Dockerfile.zed
    container_name: rabbit-nav
    working_dir: /rabbit
    volumes:
      - ./rabbit:/rabbit
    restart: unless-stopped
    command: uv run src/node/nav.py
    depends_on:
      - nats-init

  rabbit-explore:
    logging: *logging
    build:
      context: ./rabbit
      dockerfile: ./docker/Dockerfile.zed
    container_name: rabbit-explore
    working_dir: /rabbit
    volumes:
      - ./rabbit:/rabbit
    restart: unless-stopped
    command: uv run src/node/explore.py
    depends_on:
      - nats-init

  rabbit-telemetry:
    logging: *logging
    build:
      context: ./rabbit
      dockerfile: ./docker/Dockerfile.zed
    container_name: rabbit-telemetry
    privileged: true
    network_mode: host
    environment:
      - NATS_URL=nats://127.0.0.1:4222
      - WIFI_INTERFACE=wlP1p1s0
    working_dir: /rabbit
    volumes:
      - ./rabbit:/rabbit
      - /run/jtop.sock:/run/jtop.sock
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: uv run src/node/telemetry.py
    depends_on:
      - nats-init

  rabbit-ina:
    logging: *logging
    build:
      context: ./rabbit
      dockerfile: ./docker/Dockerfile.zed
    container_name: rabbit-ina
    privileged: true
    working_dir: /rabbit
    volumes:
      - ./rabbit:/rabbit
    restart: unless-stopped
    command: uv run src/node/ina.py
    depends_on:
      - nats-init

  nats-dashboard:
    logging: *logging
    image: mdawar/nats-dashboard
    container_name: nats-dashboard
    environment:
      - NATS_URL=nats://nats:4222
    ports:
      - '8000:80'
    depends_on:
      - nats
